Adding camera
Virtana/robot_tooltip_calibration pull request #2
Opened 2022-06-08 14:44 UTC by JaredMohansingh

Camera dded that takes 1 picture per second and stores in /Images.
Camera is 1.5 m overhead from base of robot.
Sharpie is on top-center of robot wrist

2022-06-13 15:03 UTC, sarika93 requested changes

2022-06-13 15:03 UTC, sarika93 commented on RobotTesting/Assets/Scripts/camscript.cs
> +//namespace UnityTipsTricks
Get rid of stale comments.

2022-06-13 15:03 UTC, sarika93 commented on RobotTesting/Assets/Scripts/camscript.cs
> +	public class camscript : MonoBehaviour
Style guide, as mentioned before, is the Google C# style guide: https://google.github.io/styleguide/csharp-style.html. 

Class names should be formatted using PascalCase, so this should be CamScript.

2022-06-13 15:03 UTC, sarika93 commented on RobotTesting/Assets/Scripts/camscript.cs
> +		public int superSize = 2;
Public variables should be PascalCase.

2022-06-13 15:03 UTC, sarika93 commented on RobotTesting/Assets/Scripts/camscript.cs
> +using System.Collections;
Inconsistent indentation. 

Indentation should be 2 spaces per style guide. Apply throughout this script as needed.

2022-06-13 15:03 UTC, sarika93 commented on RobotTesting/Assets/Scripts/camscript.cs
> +        {
No line break before opening brace, according to style guide. Apply throughout this script.

2022-06-13 15:03 UTC, sarika93 commented on RobotTesting/Assets/Scripts/camscript.cs
> +			    ScreenCapture.CaptureScreenshot($"Images/Image{_shotIndex}.png", superSize);
Fix indentation. This is not in line with the rest of this while loop.

2022-06-13 15:03 UTC, sarika93 commented on RobotTesting/Assets/Scripts/camscript.cs
> +			    ScreenCapture.CaptureScreenshot($"Images/Image{_shotIndex}.png", superSize);
What we want is not to get a screenshot, to the save an image of what our Camera visualizes. This method also makes it impossible to add a second camera that adds a different view. 

I'd recommend taking a look at Unity's [Camera](https://docs.unity3d.com/ScriptReference/Camera.html) class and saving images from a specific camera view in Unity. This is a common use case, so you should be able to find resources.

2022-06-13 15:03 UTC, sarika93 commented on RobotTesting/Assets/Scripts/camscript.cs
> +            while(true)
Unity has a game loop that runs continuously, so if you ever have to use "while (true)", this is probably bad design. Consider moving this logic into the game loop (Update or FixedUpdate; while you're at it, look up the difference between these.).

2022-06-13 15:03 UTC, sarika93 commented on RobotTesting/Assets/Scripts/camscript.cs
> +		private void Update()
Please remove empty functions.

2022-06-13 15:03 UTC, sarika93 commented on RobotTesting/Assets/Scripts/camscript.cs
> +//}
Add newline at the end of each script.

2022-06-14 15:05 UTC, sarika93 requested changes
Double check line lengths as well. Not completely done reviewing, but a few things to change here.

2022-06-14 15:05 UTC, sarika93 commented on RobotTesting/Assets/Scripts/CamScript.cs
> +    Camera overHeadCam = GetComponent<Camera>();
Let's make this a private variable since this isn't going to change and you repeat this every second.

2022-06-14 15:05 UTC, sarika93 commented on RobotTesting/Assets/Scripts/CamScript.cs
> +
Remove extra whitespace. There should be no empty lines between the last line in your function and the closing bracket. Apply throughout as necessary.

2022-06-14 15:05 UTC, sarika93 commented on RobotTesting/Assets/Scripts/CamScript.cs
> +        //Starting the repeating function that takes pictures
This comment should be above the previous line. Incorrect indentation.

2022-06-14 15:05 UTC, sarika93 commented on RobotTesting/Assets/Scripts/CamScript.cs
> +    InvokeRepeating("getCamView", 1.0f , 1.0f);
2 spaces for indentation and not one.

2022-06-14 15:05 UTC, sarika93 commented on RobotTesting/Assets/Scripts/CamScript.cs
> +  {
This bracket needs to be on the same line as the function declaration per style guide.

2022-06-14 15:05 UTC, sarika93 commented on RobotTesting/Assets/Images/0.jpg.meta
> +fileFormatVersion: 2
Add the Images folder to the .gitignore file so we don't check in 2000+ images at any point (this adds unnecessary clutter to the repo). Remove the tracking for this folder.

2022-06-14 15:05 UTC, sarika93 commented on RobotTesting/UserSettings/EditorUserSettings.asset
> +%YAML 1.1
Add the UserSettings folder to the .gitignore file as well (we added this before, but looks like it never made it into main). This is your personal Unity setup and doesn't need to be tracked; remove tracking on these files (delete them and then commit deleting them).

2022-06-14 15:05 UTC, sarika93 commented on RobotTesting/Assets/Scripts/CamScript.cs
> +	Destroy(camView);
Why not also make camView and private variable that you can reuse instead of having to destroy and recreate continuously.

2022-06-14 15:05 UTC, sarika93 commented on RobotTesting/Assets/Scripts/CamScript.cs
> +  void getCamView(){
Method names should be PascalCase.

2022-06-14 19:06 UTC, JaredMohansingh commented on RobotTesting/Assets/Scripts/CamScript.cs
> +    Camera overHeadCam = GetComponent<Camera>();
Hi, I tried moving this line out of GetCamView() so as to read:

```
private Camera overHeadCam = GetComponent<Camera>();

  void GetCamView(){
```
But now I get the error :

Assets/Scripts/CamScript.cs(9,32): error CS0236: A field initializer cannot reference the non-static field, method, or property 'Component.GetComponent<Camera>()'

2022-06-14 20:26 UTC, sarika93 commented on RobotTesting/Assets/Scripts/CamScript.cs
> +    Camera overHeadCam = GetComponent<Camera>();
GetComponent is a function so you can't use it to initialize a field. You need to call this function in Start or Awake. 

Also, private variables need an underscore before them.

2022-06-15 21:12 UTC, sarika93 requested changes
Probably the last set of changes that are required before merging. You'll need to update your render texture size whenever you confirm your camera specs but, for now, 4000 x 4000 is fine.

2022-06-15 21:12 UTC, sarika93 commented on RobotTesting/Assets/Scripts/CamScript.cs
> +	  RenderTexture.active = _overHeadCam.targetTexture;
This line and all below should have the same indentation as the above. Looks normal in VS Code though, so not sure what's going on here.

2022-06-15 21:12 UTC, sarika93 commented on RobotTesting/Packages/.gitignore
> +# This .gitignore file should be placed at the root of your Unity project directory
This file doesn't need to be here. Please remove.

2022-06-15 21:12 UTC, sarika93 commented on RobotTesting/ProjectSettings/.gitignore
> +# This .gitignore file should be placed at the root of your Unity project directory
This file doesn't need to be here. Please remove.

2022-06-15 21:12 UTC, sarika93 commented on RobotTesting/UserSettings/Layouts/default-2021.dwlt
>    m_Enabled: 1
Delete the entire UserSettings folder. This should not be tracked by git (high chance my Unity window set up is different from yours and I don't want it being over-written every time).

2022-06-15 21:12 UTC, sarika93 commented on RobotTesting/Assets/redsharpie.blend.meta
> +fileFormatVersion: 2
Because the sharpie is a blender file, this project has blender as a dependency. Either:

1. Update the README to include this OR
2. Convert this to another format that Unity can read directly (.fbx, .obj)

2022-06-15 21:12 UTC, sarika93 commented on RobotTesting/Assets/Scripts/CamScript.cs
> +	  var Bytes= _camView.EncodeToJPG();
Since we know the output type, let's declare the type explicitly, rather than use "var".

2022-06-15 21:12 UTC, sarika93 commented on RobotTesting/Assets/Scripts/CamScript.cs
> +using System.Collections;
**No action required**, but just an FYI that you can create a RenderTexture in code, and not need to have a file for it.

2022-06-15 21:12 UTC, sarika93 commented on RobotTesting/Assets/Scripts/CamScript.cs
> +
Remove this extra whitespace.

2022-06-15 21:12 UTC, sarika93 commented on RobotTesting/Assets/Scripts/CamScript.cs
> +
Remove extra line here.

2022-06-16 05:48 UTC, JaredMohansingh commented on RobotTesting/Assets/Scripts/CamScript.cs
> +	  RenderTexture.active = _overHeadCam.targetTexture;
This indentation is also not present when I open in VS Code, I only see it on github as well.

2022-06-17 15:21 UTC, sarika93 requested changes
Remove the .meta file for the URDF folder as well.

2022-06-17 15:21 UTC, sarika93 commented on RobotTesting/Assets/Scripts/CamScript.cs
> +	  _camView = new Texture2D(_overHeadCam.targetTexture.width ,
This also needs to be initialised in Start to avoid memory leaks. No need to continuously re-instantiate something that won't be any different for each of the 2000+ times we expect this function to run.

2022-06-17 15:21 UTC, sarika93 commented on RobotTesting/Assets/Scripts/CamScript.cs
> +	  _overHeadCam.Render();
I figured out the issue with these lines. The first tab is actually a tab, and not two spaces. You'll need to update all these lines accordingly. Ctrl + Shift + down or up in VS Code to have your cursor on multiple lines above or below (so you can make the same edit on multiple lines in one go).

2022-06-17 15:21 UTC, sarika93 commented on RobotTesting/Assets/Images.meta
>  fileFormatVersion: 2
Remove this file as well.

2022-06-17 18:10 UTC, sarika93 approved these changes
LGTM other than minor changes. You can merge after those changes are made. Reminder to remove the Assets/URDF.meta file.

2022-06-17 18:10 UTC, sarika93 commented on RobotTesting/Assets/Scripts/CamScript.cs
> +    byte[] Bytes = _camView.EncodeToJPG();
Nit: Local variables should be camelCase, so "bytes".

2022-06-17 18:10 UTC, sarika93 commented on RobotTesting/Assets/Scripts/CamScript.cs
> +    RenderTexture.active =currentRenText;
Nit: Space between "=" and "currentRenText"

2022-06-17 18:10 UTC, sarika93 commented on RobotTesting/Assets/Scripts/CamScript.cs
> +    _camView = new Texture2D(_overHeadCam.targetTexture.width ,
This should be on one line, since it's within the 100 character limit.

2022-06-17 18:50 UTC, merged